admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9902
dynamic_resources:
  ads_config:
    api_type: GRPC
    grpc_services:
    - envoy_grpc:
        cluster_name: xds_cluster
    transport_api_version: V3
  cds_config:
    ads: {}
  lds_config:
    ads: {}
node:
  cluster: engineering-cluster
  id: team=engineering/dp-86107bfe-0819-4c63-8859-197835cc56cc
  metadata:
    dataplane_id: 86107bfe-0819-4c63-8859-197835cc56cc
    dataplane_name: engineering-dataplane
    gateway_host: 127.0.0.1
    team: engineering
static_resources:
  clusters:
  - connect_timeout: 1s
    dns_lookup_family: V4_ONLY
    http2_protocol_options: {}
    load_assignment:
      cluster_name: xds_cluster
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 0.0.0.0
                port_value: 50051
    name: xds_cluster
    type: LOGICAL_DNS
